debug already running containers

diff --git a/.github/workflows/ci-autoup.yml b/.github/workflows/ci-autoup.yml
--- a/.github/workflows/ci-autoup.yml
+++ b/.github/workflows/ci-autoup.yml
@@ -97,7 +97,7 @@ jobs:
           DOCKER_USER: ${{ secrets.DOCKER_USER }}
           DOCKER_PASSW: ${{ secrets.DOCKER_PASSW }}
   
-  deploy-previous:
+  deploy-test-previous:
     needs: build
     runs-on: ubuntu-latest
     steps:
@@ -130,6 +130,16 @@ jobs:
           project_id: ${{ secrets.GCP_PROJECT_ID }}
           service_account_key: ${{ secrets.GCP_SA_KEY }}
           export_default_credentials: true
+      
+      - name: Stop all running containers
+        run: |
+            gcloud compute ssh ${{ env.GCP_GPU_NAME }} --zone ${{ env.GCP_GPU_ZONE }} --command "\
+            CONTAINERS=\$(docker ps -q)
+            if [ -z \"\$CONTAINERS\" ]; then
+              echo 'No containers to stop.'
+            else
+              docker stop \$CONTAINERS || echo 'Failed to stop some containers, but continuing.'
+            fi"
 
       - name: Start orchestrator server
         run: gcloud compute ssh ${{ env.GCP_GPU_NAME }} --zone ${{ env.GCP_GPU_ZONE }} --command "export BUILD_ID=${{ github.run_id }}; docker run -d --gpus all --runtime=nvidia -p ${{ env.ORCH_PORT }}:${{ env.ORCH_PORT }} -p ${{ env.LLM_PORT }}:${{ env.LLM_PORT }} -e AUTOUP_SLEEP=300 -e ENV_TOKEN_AUTOUP=dev corcelio/cicd:autoup-orchestrator-$BUILD_ID"
